CREATE DATABASE metro;
USE metro;
CREATE TABLE estacion (id)(
id MEDIUMINT UNSIGNED NOT NULL,
lat VARCHAR(14)NOT NULL,
longitud VARCHAR(15)NOT NULL,
alt MEDIUMINT NOT NULL,
PRIMARY KEY(id));

CREATE TABLE muestra(
id estacion MEDIUMINT UNSIGNED NOT NULL,
fecha DATE NOT NULL,
tempmax 
)